### PR TITLE
Add example grafana dashboard

### PR DESCRIPTION
**Pull request by sile**

### CODE REVIEW

**Comment by shinnya** [comment]
Could you upload a screenshot of your grafana dashboard?

**Comment by yuezato** [comment]
Thank you. I confirm that your dashboard json file works well.
I'd be grateful if you could write a guide to introduce and use Grafana (and Prometheus) with a simple example!!

**Comment by koba-e964** [comment]
Merging because this PR itself is fine.
Let us handle remaining tasks in other PRs.

**Comment by sile** [comment]
🙇

**Pull request merged**
